# Generated by Django 2.1.4 on 2018-12-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basescript',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='masterscenario',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='dryrundata',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dry_run_datas', to='tm_api.Machine'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('waiting', 'waiting'), ('passed', 'passed'), ('failed', 'failed'), ('warning', 'warning'), ('error', 'error'), ('unknown', 'unknown'), ('aborted', 'aborted')], default='unknown', max_length=9),
        ),
    ]
